#include<stdio.h>

int main(){
    int i,j,k,m,input;
    scanf("%d",&input);
    for(i=1;i<=input;i++){
        for(j=1;j<=25*input;j++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=5*input;m++){
            printf("#");
        }
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=4*input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=5*input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=4*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=4*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(i=1;i<=input;i++){
        for(j=1;j<=25*input;j++){
            printf(".");
        }
        printf("\n");
    }
}
