/*
name - lastname : thunyatorn jirachaisri
file name : pattern_10.c
*/

#include<stdio.h>
int main(){
    int input;
    int k;
    int m;
    scanf("%d",&input);
    for(int i=1;i<=input;i++){
        for(int j=1;j<=25*input;j++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=5*input;m++){
            printf("#");
        }
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=4*input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=5*input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(k=1;k<=input;k++){
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=4*input;m++){
            printf(".");
        }
        for(m=1;m<=input;m++){
            printf("#");
        }
        for(m=1;m<=4*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=3*input;m++){
            printf(".");
        }
        for(m=1;m<=3*input;m++){
            printf("#");
        }
        for(m=1;m<=2*input;m++){
            printf(".");
        }
        printf("\n");
    }
    for(int i=1;i<=input;i++){
        for(int j=1;j<=25*input;j++){
            printf(".");
        }
        printf("\n");
    }
}
